name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # Le indicamos a la caché exactamente dónde buscar el archivo lock
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
        
      - name: Fix SPA Routing (Copy index to 404)
        run: cp ./frontend/dist/index.html ./frontend/dist/404.html
        
      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Las acciones "uses" siempre se ejecutan desde la raíz. 
          # Debemos especificar la ruta completa hacia tu build.
          path: './frontend/dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
